### ISSUE TITLE
Remote-Write fails with import on k6

### ISSUE THREAD

**Issue by sharathfeb12** [grafana/xk6-client-prometheus-remote#18]
root@bastion:~# go version
go version go1.18 linux/amd64

root@bastion:~# cat k.js
import remote from 'k6/x/remotewrite';

root@bastion:~# k6 run k.js

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

ERRO[0000] unknown module: k6/x/remotewrite
	at go.k6.io/k6/js.(*InitContext).Require-fm (native)
	at file:///root/k.js:1:0(6)  hint="script exception"

**Comment by mstoykov** [comment]
Hi @sharathfeb12 , sorry for the slow reply.

xk6 builds a new binary called `k6` in the local directory when you run `xk6 build ....`. To run it you need to use `./k6 run  ...` isntead of `k6 run` which will run whatever `k6` is in your $PATH
